version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "8080:80"     # 宿主机 8080 -> 容器 80
    depends_on:
      - backend 
    networks:
      - app-network
    restart: unless-stopped
  llm-meter-backend:
    image: my-backend:latest
    container_name: vue-backend
    expose:
      - "15001"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped
networks:
  app-network:
    driver: bridge