FROM python:3.12.13

COPY src /app/src
COPY web /app/web
COPY .env /app/.env
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

ENTRYPOINT ["python", "app/src/server.py"]