version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: llm-meter-web
    ports:
      - "3000:3000"
    depends_on:
      - llm-meter-backend 
    networks:
      - app-network
    restart: unless-stopped
  llm-meter-backend:
    image: docker.v2.aispeech.com/aispeech/llm-meter:v0.0.1
    expose:
      - "15001"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped
networks:
  app-network:
    driver: bridge