FROM nginx:alpine

# 清理默认欢迎页文件
RUN rm -rf /usr/share/nginx/html/*

# 将编译好的 dist 目录复制到 Nginx 静态目录
COPY ./dist /usr/share/nginx/html

# 替换默认配置为自定义配置（支持 Vue Router history 模式）
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# 暴露端口
EXPOSE 3000