FROM docker.1ms.run/library/nginx
MAINTAINER wuxueliang4596@163.com

STOPSIGNAL SIGTERM

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

COPY dist /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf